### ISSUE TITLE
使用python3 main.py命令时报错

### ISSUE THREAD

**Issue by xuan-ming** [smilecc/24h-raspberry-live-on-bilibili#11]
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from service.Media import MediaService
  File "/root/blive-raspberry-master/service/Media.py", line 9, in <module>
    from util.FFmpeg import *
  File "/root/blive-raspberry-master/util/FFmpeg.py", line 2, in <module>
    from mutagen.mp3 import MP3
ModuleNotFoundError: No module named 'mutagen'

**Comment by xuan-ming** [comment]
这个问题已经解决了，但是运行python3 main.py之后遇到了新的问题具体如下：
[Media Service][ERROR] [Errno 2] No such file or directory: './resource/music/
请问这个如何解决？

**Comment by 2314933036** [comment]
> 这个问题已经解决了，但是运行python3 main.py之后遇到了新的问题具体如下：
> [Media Service][ERROR] [Errno 2] No such file or directory: './resource/music/
> 请问这个如何解决？

没有music目录你不会自己建一个?
我知道你接下来会问什么,
目录里面不会放首歌?

**Comment by inoeud** [comment]
> > 这个问题已经解决了，但是运行python3 main.py之后遇到了新的问题具体如下：
> > [Media Service][ERROR] [Errno 2] No such file or directory: './resource/music/
> > 请问这个如何解决？
> 
> 没有music目录你不会自己建一个?
> 我知道你接下来会问什么,
> 目录里面不会放首歌?

[2020-05-12 15:37:48,419][Media Service][INFO] [Music] [yhljzgt]播放结束
[2020-05-12 15:37:48,466][Media Service][INFO] [Music] 开始播放[系统]点播的[yhljzgt]
[2020-05-12 15:37:48,690][Media Service][DEBUG] ffmpeg -re -loop 1 -r 3 -t 225 -f image2 -i "./resource/img/darksouls.jpg" -i "./resource/music/yhljzgt.mp3" -vf ass="./resource/lrc/default.ass" -pix_fmt yuv420p -crf 24 -preset ultrafast -maxrate 3000k -acodec aac -b:a 192k -c:v h264_omx -f flv "rtmp://bvc.live-send.acg.tv/live-bvc/?streamname=live_37827426_7250214&key=5bbcc94853f9f00b2f8a09d3bb17fd10" 2>> ./log/ffmpeg.log
这是编码器出问题了吗？
