### ISSUE TITLE
这个问题不知道如何解决

### ISSUE THREAD

**Issue by tlj218** [smilecc/24h-raspberry-live-on-bilibili#5]
pi@raspberrypi:~/blive-raspberry $ python3 main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from util.Log import Log
  File "/home/pi/blive-raspberry/util/Log.py", line 2, in <module>
    from colorlog import ColoredFormatter
ImportError: No module named 'colorlog'

**Comment by tlj218** [comment]
pi@raspberrypi:~ $ cd blive-raspberry
pi@raspberrypi:~/blive-raspberry $ python3 main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from util.Log import Log
  File "/home/pi/blive-raspberry/util/Log.py", line 2, in <module>
    from colorlog import ColoredFormatter
ImportError: No module named 'colorlog'

**Comment by ehgen0ng** [comment]
pip3 install colorlog
